version: '3.8'
services:
  django:
    build:
      context: ./app1
      dockerfile: Dockerfile
    container_name: django-app
    ports:
      - "8000:8000"
    volumes:
      - ./app1:/app
    depends_on:
      - db

  react:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: react-app
    ports:
      - "3000:3000"
    stdin_open: true
    tty: true

  db:
    image: postgres:13
    container_name: postgres-db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Tiwari@123

volumes:
  postgres_data:
